name = "aws-wasm"
workers_dev = true

compatibility_date = "2022-10-05"
main = "build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.11"

[build]
command = "cargo install worker-build && worker-build --release"
