name = "aws-wasm"
workers_dev = true

compatibility_date = "2023-03-13"
main = "build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.14"

[build]
command = "cargo install worker-build && worker-build --release"
