name = "aws-wasm"
workers_dev = true

main = "build/worker/shim.mjs"
compatibility_date = "2025-05-31"

[vars]
WORKERS_RS_VERSION = "0.5.0"

[build]
command = "cargo install -q worker-build && worker-build --release"