name: CI

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "*.md"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: ⚡Rust Cache
        uses: Swatinem/rust-cache@v2

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Run unit tests
        run: cargo test_linux

      - name: Publish
        run: npm i wrangler && npx wrangler publish
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
